# Generated by Django 4.0.3 on 2022-06-09 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_admin', models.CharField(blank=True, max_length=30)),
                ('login', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
